p8150_hw1_wz2629
================
Wen Dai
2023-09-20

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(moderndive)
```

# Problem 1:

This problem focuses the use of inline R code, plotting, and the
behavior of ggplot for variables of different types.

``` r
data("early_january_weather")
```

1.1) Write a short description of the dataset using inline R code;
accessing the dataset help file can be informative.

``` r
nrow(early_january_weather)
```

    ## [1] 358

``` r
ncol(early_january_weather)
```

    ## [1] 15

``` r
summary(early_january_weather)
```

    ##     origin               year          month        day              hour      
    ##  Length:358         Min.   :2013   Min.   :1   Min.   : 1.000   Min.   : 0.00  
    ##  Class :character   1st Qu.:2013   1st Qu.:1   1st Qu.: 4.000   1st Qu.: 6.00  
    ##  Mode  :character   Median :2013   Median :1   Median : 8.000   Median :11.50  
    ##                     Mean   :2013   Mean   :1   Mean   : 8.039   Mean   :11.53  
    ##                     3rd Qu.:2013   3rd Qu.:1   3rd Qu.:12.000   3rd Qu.:17.75  
    ##                     Max.   :2013   Max.   :1   Max.   :15.000   Max.   :23.00  
    ##                                                                                
    ##       temp            dewp           humid           wind_dir    
    ##  Min.   :24.08   Min.   : 8.96   Min.   : 32.86   Min.   :  0.0  
    ##  1st Qu.:33.98   1st Qu.:19.94   1st Qu.: 51.34   1st Qu.:140.0  
    ##  Median :39.02   Median :26.06   Median : 61.67   Median :240.0  
    ##  Mean   :39.58   Mean   :28.06   Mean   : 65.48   Mean   :208.2  
    ##  3rd Qu.:44.96   3rd Qu.:35.06   3rd Qu.: 78.68   3rd Qu.:290.0  
    ##  Max.   :57.92   Max.   :53.06   Max.   :100.00   Max.   :360.0  
    ##                                                   NA's   :5      
    ##    wind_speed       wind_gust         precip            pressure   
    ##  Min.   : 0.000   Min.   :16.11   Min.   :0.000000   Min.   :1011  
    ##  1st Qu.: 5.754   1st Qu.:19.56   1st Qu.:0.000000   1st Qu.:1018  
    ##  Median : 8.055   Median :21.86   Median :0.000000   Median :1022  
    ##  Mean   : 8.226   Mean   :22.53   Mean   :0.002039   Mean   :1023  
    ##  3rd Qu.:11.508   3rd Qu.:25.32   3rd Qu.:0.000000   3rd Qu.:1027  
    ##  Max.   :24.166   Max.   :31.07   Max.   :0.190000   Max.   :1034  
    ##                   NA's   :308                        NA's   :38    
    ##      visib          time_hour                     
    ##  Min.   : 0.120   Min.   :2013-01-01 01:00:00.00  
    ##  1st Qu.: 9.000   1st Qu.:2013-01-04 19:15:00.00  
    ##  Median :10.000   Median :2013-01-08 12:30:00.00  
    ##  Mean   : 8.515   Mean   :2013-01-08 12:28:09.39  
    ##  3rd Qu.:10.000   3rd Qu.:2013-01-12 05:45:00.00  
    ##  Max.   :10.000   Max.   :2013-01-15 23:00:00.00  
    ## 

``` r
mean(pull(early_january_weather,temp))
```

    ## [1] 39.58212

Answer:

- This dataset is hourly meteorological data for LGA, JFK and EWR for
  the month of January 2013. It contains 15 variables including: origin,
  year, month, day, hour, temp, dewp, humid, wind_dir, wind_speed,
  wind_gust, precip, pressure, visib, time_hour.

- The important variables are:

  - temp:Temperature in F. (Min=24.08F; Max=57.92F; Mean= 39.58F;
    Median=39.02F, Q1=33.98F, Q3=44.96F)

  - time_hour:Date and hour of the recording as a POSIXct data.(Min:
    2013-01-01 ; Max:2013-01-15; Mean=2013-01-08; Median=2013-01-08;
    Q1=2013-01-04; Q3= 2013-01-12)

  - humid:Relative humidity.(Min=32.86, Max=100.00, Mean=65.48,
    Median=61.67, Q1=51.34, Q3=78.68)

  - pressure:Sea level pressure in millibars. (Min=1011 millibars,
    Max=1034 millibars, Mean=1023 millibars, Median=1022 millibars,
    Q1=1018 millibars, Q3=1027 millibars)

  - precip:Precipitation, in inches.(Min=0 inches, max=0 inches,
    mean=0.002 inches, median=0inches, Q1=0 inches and Q3=0 inches)

- The size of the dataset contains 358 rows and 15 columns.

- the mean temperature is 39.5821229 F.

1.2) Make a scatterplot of temp (y) vs time_hour (x); color points using
the humid variabl. Descrive patterns that are apparent in this plot.
Export your scatterplot to your project directory using ggsave.

``` r
xy_scatterplot<-ggplot(data=early_january_weather, aes(x=time_hour, y=temp, color=humid))+geom_point()+labs(title="scatterplot of time_hour vs temp",x="time_hour",y="temp")
ggsave("early_january_weather.pdf")
```

    ## Saving 7 x 5 in image

Answer: Although there were intermittent fluctuations in temperature
throughout the day, the daily average temperature exhibited a consistent
upward trend from January 1st to January 14, followed by a subsequent
decline. Also, a rising trend in humidity was observed, commencing
around January 7 and reaching its peak approximately on January 14.

# Problem 2:

This problem is intended to emphasize variable types and introduce
coercion; some awareness of how R treats numeric, character, and factor
variables is necessary for working with these data types in practice.

1.1) Create a data frame

``` r
prob2_df=
  tibble(
    rand=rnorm(10),
    logvec=rand>10,
    charvec=c("I","L","O","V","E","U","D","A","T","A"),
    facvec=factor(c("A","B","C","A","C","B","B","A","A","A"))
  )
```

``` r
mean(pull(prob2_df,rand))
```

    ## [1] -0.3979797

``` r
mean(pull(prob2_df,logvec))
```

    ## [1] 0

``` r
mean(pull(prob2_df,charvec))
```

    ## [1] NA

``` r
mean(pull(prob2_df,facvec))
```

    ## [1] NA

Answer:

- The mean of a random sample “rand” is -0.3979797
- The mean of logical vector “logvec” is 0
- For character vector and factor vector the mean function doesn’t work
  because because these data types represent categorical or qualitative
  data, not quantitative data that can be arithmetically averaged.

2.2 Convert variables from one type to another. Write a code chunk that
applies the as.numeric function to the logical, character, and factor
variables. What happens, and why? Does this help explain what happens
when you try to take the mean?

``` r
rand_logvec<-as.numeric(pull(prob2_df, logvec))
rand_charvec<-as.numeric(pull(prob2_df,charvec))
rand_facvect<-as.numeric(pull(prob2_df,facvec))
```

Answer:

- After use “as.numeric” to convert variables from one type to
  another.Here is what happens:

  - We can convert a logical variable to a numeric vector.TRUE is
    typically converted to 1, and FALSE is converted to 0.
  - We can convert vector to a numeric variable, because it converts the
    levels to their underlying numeric representation, which is
    typically the integer index of each level.
  - When we try to convert character variable,R will attempt to convert
    each character element to a numeric value, but if the character
    elements do not represent valid numeric values, you will get result
    as “NA”.

- Yes, it does help to explain what happen what happens when I take the
  mean:

  - We are able to calculate mean of a random variable in R, as random
    variables typically represent numerical data.

  - We are able to calculate the mean of logical values. R treats TRUE
    as 1 and FALSE as 0, so the mean represents the proportion of TRUE
    values in the data.

  - We are unable to directly calculate the mean of a factor or
    character variable in R because these data types are categorical. It
    requires some additional steps to calculate the mean of a factor, we
    need to convert it to numeric values.
